on:
  workflow_dispatch:
    inputs:
      wave:
        description: 'ReSharper Wave (e.g. 243 for 2024.3.x)'
        required: true
        default: '100'
        type: string
      version:
        description: 'Plugin Version (e.g. 2024.3.1)'
        required: true
        default: '2025.1.0'
        type: string
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare environment
      working-directory: Frontend
      run: ./gradlew :prepare
      shell: bash

    - name: Build ReSharper plugin
      working-directory: Backend/ReSharperPlugin
      run: |
        $wave = '${{ github.event.inputs.wave }}'
        $version = '${{ github.event.inputs.version }}'
        ./build.ps1 pack -Configuration Release -WaveVersion $wave -Version $version
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: resharper-plugin
        path: Backend/ReSharperPlugin/artifacts/Release/

# to get the notification email in any case
    - name: Build Failed Successfully
      run: |
        echo "💥 Task failed successfully! 💥"
        exit 1
